import type { Tenant, TenantConfig } from '@/lib/types';

// ============================================================
// Mock Tenant Data for Super Admin Panel
// ============================================================

export const mockTenants: Tenant[] = [
  {
    id: 'tenant-1',
    name: 'Shree Krishna Dairy',
    slug: 'shree-krishna-dairy',
    contactPerson: 'Rajesh Patel',
    email: 'rajesh@shreekrishnadairy.in',
    phone: '+91 98250 41230',
    address: {
      line1: '12, Industrial Estate, Naroda Road',
      line2: 'Near GIDC Gate No. 3',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '382330',
      country: 'India',
    },
    logo: '/logos/shree-krishna.png',
    status: 'active',
    plan: 'premium',
    agencyCount: 5,
    config: {
      features: {
        gpsTracking: true,
        pushNotifications: true,
        advancedAnalytics: true,
        bulkImport: true,
        photoProofDelivery: true,
      },
      limits: {
        maxAgencies: 10,
        maxEmployees: 50,
        maxShopkeepers: 500,
      },
      branding: {
        primaryColor: '#1E40AF',
        secondaryColor: '#F59E0B',
        logo: '/logos/shree-krishna.png',
      },
      invoiceSettings: {
        taxEnabled: true,
        taxPercentage: 5,
        invoicePrefix: 'SKD',
        invoiceNumberFormat: 'SKD-{YYYY}-{SEQ}',
        termsAndConditions: 'Payment due within 15 days of invoice date.',
      },
      notificationChannels: ['in_app', 'push'],
      defaultLanguage: 'gu',
      timezone: 'Asia/Kolkata',
      currencyFormat: 'INR',
    },
    createdAt: '2025-08-15T09:30:00.000Z',
    updatedAt: '2026-01-20T14:45:00.000Z',
  },
  {
    id: 'tenant-2',
    name: 'Gujarat Milk Co',
    slug: 'gujarat-milk-co',
    contactPerson: 'Amit Shah',
    email: 'amit@gujaratmilkco.in',
    phone: '+91 97270 58432',
    address: {
      line1: '45, Vidya Nagar Main Road',
      city: 'Anand',
      state: 'Gujarat',
      pincode: '388001',
      country: 'India',
    },
    status: 'active',
    plan: 'enterprise',
    agencyCount: 12,
    config: {
      features: {
        gpsTracking: true,
        pushNotifications: true,
        advancedAnalytics: true,
        bulkImport: true,
        photoProofDelivery: true,
      },
      limits: {
        maxAgencies: 25,
        maxEmployees: 100,
        maxShopkeepers: 2000,
      },
      branding: {
        primaryColor: '#047857',
        secondaryColor: '#FBBF24',
        logo: '/logos/gujarat-milk.png',
      },
      invoiceSettings: {
        taxEnabled: true,
        taxPercentage: 5,
        invoicePrefix: 'GMC',
        invoiceNumberFormat: 'GMC-{YYYY}-{SEQ}',
        termsAndConditions: 'Payment due within 30 days of invoice date.',
      },
      notificationChannels: ['in_app', 'push'],
      defaultLanguage: 'gu',
      timezone: 'Asia/Kolkata',
      currencyFormat: 'INR',
    },
    createdAt: '2025-07-22T06:15:00.000Z',
    updatedAt: '2026-02-05T10:30:00.000Z',
  },
  {
    id: 'tenant-3',
    name: 'Amul Fresh Distributors',
    slug: 'amul-fresh-distributors',
    contactPerson: 'Priya Mehta',
    email: 'priya@amulfreshdist.in',
    phone: '+91 98765 12340',
    address: {
      line1: '78, Linking Road, Bandra West',
      line2: 'Opposite National College',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
      country: 'India',
    },
    logo: '/logos/amul-fresh.png',
    status: 'active',
    plan: 'standard',
    agencyCount: 3,
    config: {
      features: {
        gpsTracking: true,
        pushNotifications: false,
        advancedAnalytics: false,
        bulkImport: true,
        photoProofDelivery: false,
      },
      limits: {
        maxAgencies: 5,
        maxEmployees: 25,
        maxShopkeepers: 200,
      },
      branding: {
        primaryColor: '#DC2626',
        secondaryColor: '#3B82F6',
      },
      invoiceSettings: {
        taxEnabled: true,
        taxPercentage: 12,
        invoicePrefix: 'AFD',
        invoiceNumberFormat: 'AFD-{YYYY}-{SEQ}',
      },
      notificationChannels: ['in_app'],
      defaultLanguage: 'en',
      timezone: 'Asia/Kolkata',
      currencyFormat: 'INR',
    },
    createdAt: '2025-09-10T11:00:00.000Z',
    updatedAt: '2026-01-15T08:20:00.000Z',
  },
  {
    id: 'tenant-4',
    name: 'Nandini Dairy Products',
    slug: 'nandini-dairy-products',
    contactPerson: 'Suresh Gowda',
    email: 'suresh@nandinidairy.in',
    phone: '+91 99001 67845',
    address: {
      line1: '23, MG Road, Shivajinagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      country: 'India',
    },
    status: 'active',
    plan: 'premium',
    agencyCount: 7,
    config: {
      features: {
        gpsTracking: true,
        pushNotifications: true,
        advancedAnalytics: true,
        bulkImport: true,
        photoProofDelivery: true,
      },
      limits: {
        maxAgencies: 10,
        maxEmployees: 50,
        maxShopkeepers: 500,
      },
      branding: {
        primaryColor: '#7C3AED',
        secondaryColor: '#10B981',
        logo: '/logos/nandini.png',
      },
      invoiceSettings: {
        taxEnabled: true,
        taxPercentage: 5,
        invoicePrefix: 'NDP',
        invoiceNumberFormat: 'NDP-{YYYY}-{SEQ}',
        termsAndConditions: 'Payment due within 7 days.',
      },
      notificationChannels: ['in_app', 'push'],
      defaultLanguage: 'en',
      timezone: 'Asia/Kolkata',
      currencyFormat: 'INR',
    },
    createdAt: '2025-10-05T13:45:00.000Z',
    updatedAt: '2026-02-01T16:10:00.000Z',
  },
  {
    id: 'tenant-5',
    name: 'Mother Dairy Express',
    slug: 'mother-dairy-express',
    contactPerson: 'Vikram Singh',
    email: 'vikram@motherdairyexpress.in',
    phone: '+91 98111 23456',
    address: {
      line1: '56, Connaught Place, Block A',
      line2: 'Inner Circle',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110001',
      country: 'India',
    },
    status: 'inactive',
    plan: 'basic',
    agencyCount: 1,
    config: {
      features: {
        gpsTracking: false,
        pushNotifications: false,
        advancedAnalytics: false,
        bulkImport: false,
        photoProofDelivery: false,
      },
      limits: {
        maxAgencies: 2,
        maxEmployees: 10,
        maxShopkeepers: 50,
      },
      branding: {
        primaryColor: '#059669',
      },
      invoiceSettings: {
        taxEnabled: false,
        taxPercentage: 0,
        invoicePrefix: 'MDE',
        invoiceNumberFormat: 'MDE-{YYYY}-{SEQ}',
      },
      notificationChannels: ['in_app'],
      defaultLanguage: 'hi',
      timezone: 'Asia/Kolkata',
      currencyFormat: 'INR',
    },
    createdAt: '2025-11-20T08:00:00.000Z',
    updatedAt: '2026-01-10T12:30:00.000Z',
  },
  {
    id: 'tenant-6',
    name: 'Verka Punjab Dairy',
    slug: 'verka-punjab-dairy',
    contactPerson: 'Harpreet Kaur',
    email: 'harpreet@verkapunjab.in',
    phone: '+91 98140 77821',
    address: {
      line1: '89, Sector 17, Industrial Area',
      city: 'Chandigarh',
      state: 'Punjab',
      pincode: '160017',
      country: 'India',
    },
    logo: '/logos/verka-punjab.png',
    status: 'suspended',
    plan: 'standard',
    agencyCount: 2,
    config: {
      features: {
        gpsTracking: true,
        pushNotifications: false,
        advancedAnalytics: false,
        bulkImport: true,
        photoProofDelivery: false,
      },
      limits: {
        maxAgencies: 5,
        maxEmployees: 25,
        maxShopkeepers: 200,
      },
      branding: {
        primaryColor: '#B91C1C',
        secondaryColor: '#FBBF24',
        logo: '/logos/verka-punjab.png',
      },
      invoiceSettings: {
        taxEnabled: true,
        taxPercentage: 5,
        invoicePrefix: 'VPD',
        invoiceNumberFormat: 'VPD-{YYYY}-{SEQ}',
      },
      notificationChannels: ['in_app'],
      defaultLanguage: 'hi',
      timezone: 'Asia/Kolkata',
      currencyFormat: 'INR',
    },
    createdAt: '2025-12-01T10:15:00.000Z',
    updatedAt: '2026-01-28T09:00:00.000Z',
  },
  {
    id: 'tenant-7',
    name: 'Parag Milk Foods',
    slug: 'parag-milk-foods',
    contactPerson: 'Devendra Joshi',
    email: 'devendra@paragmilk.in',
    phone: '+91 98234 56712',
    address: {
      line1: '34, Hinjawadi IT Park Road',
      line2: 'Phase 2, Rajiv Gandhi Infotech Park',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411057',
      country: 'India',
    },
    status: 'active',
    plan: 'standard',
    agencyCount: 4,
    config: {
      features: {
        gpsTracking: true,
        pushNotifications: true,
        advancedAnalytics: false,
        bulkImport: true,
        photoProofDelivery: true,
      },
      limits: {
        maxAgencies: 5,
        maxEmployees: 25,
        maxShopkeepers: 200,
      },
      branding: {
        primaryColor: '#2563EB',
        secondaryColor: '#F97316',
      },
      invoiceSettings: {
        taxEnabled: true,
        taxPercentage: 12,
        invoicePrefix: 'PMF',
        invoiceNumberFormat: 'PMF-{YYYY}-{SEQ}',
        termsAndConditions: 'Net 15 days from date of invoice.',
      },
      notificationChannels: ['in_app', 'push'],
      defaultLanguage: 'en',
      timezone: 'Asia/Kolkata',
      currencyFormat: 'INR',
    },
    createdAt: '2025-12-18T15:30:00.000Z',
    updatedAt: '2026-02-08T11:45:00.000Z',
  },
];

// ============================================================
// Tenant Config Map (keyed by tenant ID)
// ============================================================

export const mockTenantConfigs: Record<string, TenantConfig> = Object.fromEntries(
  mockTenants.map((tenant) => [tenant.id, tenant.config])
);
